### ISSUE TITLE
Crash when testing

### ISSUE THREAD

**Issue by patrikhson** [Netnod/robust-tjanst#78] opened 2022-01-28 12:35 UTC
When I test frobbit.se from an iPhone I get the following crash:

```
TypeError

          TypeError: Cannot read property 'map' of undefined
    at module.exports (/app/packages/tests/tests/zonemaster/messages.js:5:8)
    at buildGroups (/app/packages/web/src/tests.js:25:30)
    at /app/packages/web/src/tests.js:102:20
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.createConnection (/app/node_modules/slonik/dist/src/factories/createConnection.js:97:18)
    at async showTest (/app/packages/web/src/tests.js:90:3)
    at async /app/packages/web/src/index.js:150:3
    at async /app/packages/web/src/index.js:41:5
    at async session (/app/node_modules/koa-session/index.js:41:7)
    at async logger (/app/node_modules/koa-logger/index.js:67:7)
```

**Comment by mull** [comment] 2022-01-28 12:40
Fixed by #70 (caused by Zonemaster timing out which may be remedied by c85c2bc182b41386037699a533a83f2dac56061b)

**Closed by mull** 2022-01-28 12:40 UTC
